app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
products:
    type:   rest
    resource:   Warehouse\DataBundle\Controller\ProductController
    
warehouse:
    type: rest
    resource:   Warehouse\DataBundle\Controller\WarehouseController

list:
    type: rest
    resource:   Warehouse\DataBundle\Controller\ListController