# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    product_functions:
        class: Warehouse\DataBundle\DataFunctions\ProductFunctions
        arguments: 
            [@doctrine.orm.entity_manager, @serializer]
            
    warehouse_functions:
        class: Warehouse\DataBundle\DataFunctions\WarehouseFunctions
        arguments:
            [@doctrine.orm.entity_manager, @serializer]
            
    list_functions:
        class: Warehouse\DataBundle\DataFunctions\ListFunctions
        arguments:
            [@doctrine.orm.entity_manager, @serializer, @warehouse_functions]